# WispSMP Configuration File

# Spawn location for revived players
spawn:
  world: "world"  # Change this to your world name
  x: 0.0
  y: 64.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0

# Player lives data will be stored here automatically
# Format: players.<uuid>.lives: <number>
players: {}